export default Globals = {
  'domain':'www.kirim.com',
  'login_customer_id':'',
  'login_customer_type':'',
  'latitude ':'',
  'longitude':'',
  'login_type':'',
  'company_id':'',
  "login_customer_name":"Kirim Customer",
  "login_user_language":'en',
  'login_porter_id':'',
  'login_porter_name':'Kirim Porter',
  'api_key' : 'KIRIM@|-||_!$',
  'api_key_parsel' : 'test',
  'CUSTOMER_IMAGE':'assets/upload/customer_profile/',
  'CITY_ADMIN_IMAGE':'assets/upload/cityadmin_profile/',
  'CUSTOMER_IMAGE_THUMB':'assets/upload/customer_profile/thumb/',
  'PORTER_IMAGE':'assets/upload/porter/profile/',
  'PORTER_IMAGE_THUMB':'assets/upload/porter/profile/thumb/',
  'SIGN_IMAGE':'assets/upload/porter/sign/',
  'SIGN_IMAGE_THUMB':'assets/upload/porter/sign/thumb/',
  'BANNER_IMAGE':'assets/upload/banner/',
  'BANNER_IMAGE_THUMB':'assets/upload/banner/thumb/',
  'CATEGORY_IMAGE':'assets/upload/category/',
  'CATEGORY_IMAGE_THUMB':'assets/upload/category/thumb/',
  'SHIPPED_IMAGE':'images/shipped/',
  'VEHICLE_IMAGE':'assets/images/vehicle/',
  'PRODUCTANDSERVICE':'assets/upload/product_services/',
  'SHIPPED_ITEM_TYPE_IMAGE':'images/shipped_item_type/',
  'ITEM_IMAGE':'ship/',
  'CLAIM_IMAGE':'assets/upload/claim/',
  'PARCEL_IMAGE':'assets/upload/parcel_image/',
  'PARCEL_IMAGE_THUMB':'assets/upload/parcel_image/thumb/',
  'CLAIM_IMAGE_THUMB':'assets/upload/claim/thumb/',
  'ORDER_BARCODE':'assets/upload/',
  'ORDER_BARCODE_IMAGE':'barcode/',
  'ITEM_IMAGE_THUMB':'ship/',
  'base_url':'http://localhost:1098/',
  'assets_url':'http://localhost:8000/assets/',
  'storage_url':'http://localhost:8000/storage/uploads/',
  'key':'czhVx38Su0WIXJsVP0auaLLAKebyZ3D3',
  'iv':'czhVx38Su0WIXJsV',
  'pagesize':'10',
  "total_swipe"       :  "5",
  "email_id"          :  "kirimsmtp@gmail.com",
  "email_pass"        :  "kirimsmtp@123",
  "apn_key_id": "H3GAA23U4F",
  "apn_team_id" :"8W6DRQFN55",
  "p8_name":"./certificate/AuthKey_H3GAA23U4F.p8",
  "bundle_customer_id":"com.kirim.customer",
  "bundle_porter_id":"com.kirim.porter",
  "APP_NAME":"KIRIM",
  "push_key":'AIzaSyD9wBG7Sjdh_9A8G6i_B9Qqoin5_ouSSpo',
  "google_browser_key":"AIzaSyCaZj9s7AYdD8vJzxdvbZfZPzLG521MEr0",
  "kirim_location_radius":25,
  "gateway_api" : "HJAy8bR5M1U-gMzryH8wvfgQ6EoY4Q8QO450Uo6mkM",
  "currency_symbol": "$",
  "currency_name": "USD",
}


